/* Published research is separate from the browser-local personal workspace. */
window.MindMarket = (() => {
  'use strict';
  let data, error = '', tab = 'overview';
  const filters = {query:'',region:'',country:'',field:'',tool:'',level:'',mode:'',employment:'',salary:'',fit:'Recommended review',track:''};
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const unique = values => [...new Set(values)].sort((a,b)=>a.localeCompare(b));
  const count = (jobs,key) => Object.entries(jobs.reduce((out,j)=>{for(const v of Array.isArray(j[key])?j[key]:[j[key]])out[v]=(out[v]||0)+1;return out;},{})).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
  const recommended = j => ['Strong technical fit','Potential fit'].includes(j.fit?.band);
  const rank = {'Strong technical fit':0,'Potential fit':1,Stretch:2,'Lower priority':3};
  const selected = () => (data?.jobs||[]).filter(j => Object.entries(filters).every(([key,value])=> !value || (key==='query' ? [j.title,j.company,j.country,j.location,j.summary,j.notes,j.fit?.track,...j.tools].join(' ').toLowerCase().includes(value.toLowerCase()) : key==='tool' ? j.tools.includes(value) : key==='salary' ? Boolean(j.salary) : key==='fit' ? value==='Recommended review'?recommended(j):j.fit?.band===value : key==='track' ? j.fit?.track===value : j[key]===value))).sort((a,b)=>(rank[a.fit?.band]??9)-(rank[b.fit?.band]??9)||a.company.localeCompare(b.company));
  const salary = j => j.salary ? `${j.salary.currency} ${j.salary.min.toLocaleString('en-GB')}${j.salary.max?'–'+j.salary.max.toLocaleString('en-GB'):'+'} / ${j.salary.period} · ${j.salary.basis}` : 'Salary not disclosed';
  function home(){return `<button class="research-entry" data-action="navigate" data-view="market"><span class="research-entry-icon">↗</span><span><small>RESEARCH COLLECTION · EUROPE & ASIA</small><strong>Job observatory</strong><span>${data?`${data.jobs.length} linked vacancies · ${unique(data.jobs.map(j=>j.country)).length} countries`:'Vacancies, geography and toolset dashboards'} · snapshot 23 Sep 2026</span></span><span aria-hidden="true">→</span></button>`;}
  function select(key,label,values){return `<label>${label}<select data-market-filter="${key}" aria-label="${label}"><option value="">${key==='fit'?'All reviewed roles':'All '+label.toLowerCase()}</option>${values.map(v=>`<option ${filters[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
  function render(){
    if(!data)return `<section class="market"><h1>Job observatory</h1><p role="status">${error?esc(error):'Loading the research collection…'}</p>${error?'<button class="primary-button" data-market-action="retry">Retry loading research</button>':''}</section>`;
    return `<section class="market" aria-label="Job market research"><div class="eyebrow"># job-market / opportunities</div><div class="page-heading"><h1>Job observatory</h1><button class="secondary-button" data-market-action="export">↓ Export results</button></div><p class="subtitle">Explore real vacancies. Understand the patterns. Follow the evidence.</p><div class="market-notice"><span class="snapshot-dot"></span><strong>Snapshot · 23 Sep 2026</strong><span>${data.jobs.length} ads across ${unique(data.jobs.map(j=>j.country)).length} countries. Counts describe this sample, not total market demand.</span></div><div class="market-tabs" role="tablist" aria-label="Research views">${[['overview','Overview'],['vacancies','Vacancies'],['profile','Career fit'],['sources','Sources & method']].map(([id,label])=>`<button id="market-tab-${id}" role="tab" aria-controls="market-panel" aria-selected="${tab===id}" tabindex="${tab===id?0:-1}" data-market-tab="${id}">${label}${id==='vacancies'?` <span>${data.jobs.length}</span>`:''}</button>`).join('')}</div><div id="market-panel" role="tabpanel" aria-labelledby="market-tab-${tab}">${tab==='profile'?profileView():tab==='sources'?sources():`${profileBanner()}<div class="market-filters"><label class="market-search">Search vacancies<input data-market-filter="query" type="search" value="${esc(filters.query)}" placeholder="Role, employer, city, skill…"></label>${select('region','Regions',['Europe','Asia'])}${select('country','Countries',unique(data.jobs.filter(j=>!filters.region||j.region===filters.region).map(j=>j.country)))}${select('tool','Tools',unique(data.jobs.flatMap(j=>j.tools)))}${select('fit','Profile fit',['Recommended review','Strong technical fit','Potential fit','Stretch','Lower priority'])}${select('track','Career tracks',unique(data.jobs.map(j=>j.fit?.track).filter(Boolean)))}<details class="more-filters" ${['field','level','mode','employment','salary'].some(k=>filters[k])?'open':''}><summary>More filters <span>field · seniority · arrangement · salary</span></summary><div class="filter-grid">${select('field','Fields',unique(data.jobs.map(j=>j.field)))}${select('level','Levels',unique(data.jobs.map(j=>j.level)))}${select('mode','Arrangements',unique(data.jobs.map(j=>j.mode)))}${select('employment','Employment types',unique(data.jobs.map(j=>j.employment)))}<label class="salary-check"><input type="checkbox" data-market-filter="salary" ${filters.salary?'checked':''}> Disclosed salary only</label></div></details></div><div id="market-results">${results()}</div>`}</div></section>`;
  }
  function bars(jobs,key,label,filterKey=key,limit=100){const rows=count(jobs,key).slice(0,limit),max=rows[0]?.[1]||1;return `<section class="market-card"><h2>${label}</h2><p>Ads in the current selection${key==='tools'?' · overlapping mentions':''}</p><div class="market-bars">${rows.map(([name,n])=>`<button class="market-bar" data-market-facet="${filterKey}" data-value="${esc(name)}" aria-label="Filter ${esc(name)}: ${n} ads"><span>${esc(name)}</span><i><b style="width:${n/max*100}%"></b></i><strong>${n}</strong></button>`).join('')}</div></section>`;}
  function results(){const jobs=selected();return `<div class="market-result-line"><span role="status" aria-live="polite"><strong>${jobs.length}</strong> of ${data.jobs.length} ads · ${unique(jobs.map(j=>j.country)).length} countries</span><button class="text-button" data-market-action="clear">Reset filters</button></div>${Object.entries(filters).filter(([,v])=>v).length?`<div class="active-filters">${Object.entries(filters).filter(([,v])=>v).map(([k,v])=>`<button data-market-clear="${k}" aria-label="Remove ${esc(k)} filter">${esc(k==='salary'?'Salary disclosed':v)} ×</button>`).join('')}</div>`:''}${!jobs.length?'<div class="empty-state"><h2>No matching vacancies</h2><p>Try another combination or reset the filters. Missing countries are gaps in this sample.</p><button class="primary-button" data-market-action="clear">Show all vacancies</button></div>':tab==='vacancies'?`<div class="vacancy-list">${jobs.map(card).join('')}</div>`:overview(jobs)}`;}
  function overview(jobs){const europe=jobs.filter(j=>j.region==='Europe').length,disclosed=jobs.filter(j=>j.salary).length;const countries=count(jobs,'country'),toolCounts=count(jobs,'tools'),top=countries[0],topTool=toolCounts[0],tied=countries.filter(([,n])=>n===top[1]).map(([name])=>name),tiedTools=toolCounts.filter(([,n])=>n===topTool[1]).map(([name])=>name);return `<div class="market-kpis">${[[jobs.length,'Collected ads','Distinct listings, not headcount'],[europe,'Europe',`${jobs.length-europe} in Asia`],[unique(jobs.map(j=>j.company)).length,'Employers / agencies',`${unique(jobs.map(j=>j.country)).length} represented countries`],[disclosed,'Salary disclosed','Original currencies and periods']].map(([n,label,note])=>`<div><strong>${n}</strong><span>${label}</span><small>${note}</small></div>`).join('')}</div><div class="market-takeaway"><span>IN THIS SELECTION</span><p><strong>${esc(tied.join(', '))}</strong> ${tied.length>1?'tie for the most collected ads':'has the most collected ads'} (${top[1]}${tied.length>1?' each':''}). <strong>${esc(tiedTools.join(', '))}</strong> ${tiedTools.length>1?'tie as the most-mentioned tools':'is the most-mentioned tool'} (${topTool[1]} ads). Search coverage and employer mix affect both rankings.</p></div>${worldMap(jobs)}<div class="market-chart-grid">${bars(jobs,'country','Where are the collected roles?')}${bars(jobs,'tools','Which tools appear?','tool',10)}${bars(jobs,'field','What work is being advertised?')}${bars(jobs,'level','Who are the roles for?')}${bars(jobs,'mode','How is work arranged?')}${bars(jobs,'employment','Employment types')}</div>${matrix(jobs)}<section class="market-card"><div class="market-section-heading"><h2>Follow the listings</h2><button class="text-button" data-market-tab="vacancies">View ${jobs.length} vacancies →</button></div><p>Tools include preferred and alternative platforms. Open a listing for requirements and source details.</p>${jobs.slice(0,3).map(card).join('')}</section>`;}
  function matrix(jobs){const countries=count(jobs,'country'),tools=count(jobs,'tools').slice(0,7).map(([name])=>name);return `<section class="market-card"><h2>Country × toolset</h2><p>Seven most-mentioned tools in this selection. Each cell counts ads mentioning that tool; columns overlap.</p><div class="market-table-scroll"><table class="market-matrix"><caption class="sr-only">Collected job advertisements by country and mentioned tool</caption><thead><tr><th scope="col">Country</th>${tools.map(t=>`<th scope="col">${esc(t)}</th>`).join('')}</tr></thead><tbody>${countries.map(([c])=>`<tr><th scope="row">${esc(c)}</th>${tools.map(t=>{const n=jobs.filter(j=>j.country===c&&j.tools.includes(t)).length;return `<td>${n?`<button data-market-country="${esc(c)}" data-market-tool="${esc(t)}" class="heat-${Math.min(n,3)}" aria-label="${esc(c)}, ${esc(t)}: ${n} ads">${n}</button>`:'<span aria-label="No collected ads">—</span>'}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
  function worldMap(jobs){return `<section class="market-card world-map-section" aria-label="Vacancies around the world"><div class="world-map-heading"><div><h2>Vacancies around the world</h2><p>Country totals follow your filters. Select a highlighted country to explore its listings.</p></div><span>GEOGRAPHIC VIEW</span></div><mind-world-map data-counts="${esc(JSON.stringify(Object.fromEntries(count(jobs,'country'))))}" data-maximum="${Math.max(...count(data.jobs,'country').map(([,n])=>n))}"></mind-world-map></section>`;}
  function card(j){const old=j.postedAt&&((Date.parse(data.researchedAt)-Date.parse(j.postedAt))/86400000)>180;return `<article class="vacancy-card" id="vacancy-${esc(j.id)}"><div class="vacancy-heading"><div><div class="vacancy-company">${esc(j.company)} <span>· ${esc(j.country)}</span></div><h2><a href="${esc(j.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(j.title)} ↗</a></h2></div><span class="vacancy-field">${esc(j.field)}</span></div>${fitSummary(j)}<div class="vacancy-meta">${[j.location,j.level,j.mode,j.employment].map(v=>`<span>${esc(v)}</span>`).join('')}</div><p>${esc(j.summary)}</p><div class="vacancy-tools">${j.tools.map(t=>`<button data-market-facet="tool" data-value="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="vacancy-bottom"><strong class="${j.salary?'salary-disclosed':''}">${esc(salary(j))}</strong><a href="${esc(j.sourceUrl)}" target="_blank" rel="noopener noreferrer">View source & apply ↗</a></div><details><summary>Requirements & verification${old?' · older posting':''}</summary><dl><dt>Experience</dt><dd>${esc(j.experience)}</dd><dt>Notes</dt><dd>${esc(j.notes||'No additional restrictions recorded; consult the original listing.')}</dd><dt>Published</dt><dd>${esc(j.postedAt||'Not stated — age unknown')}${old?' · more than six months before this check':''}</dd><dt>Checked</dt><dd>${j.checkedAt} · ${esc(j.status)} · ${esc(j.sourceType)}</dd><dt>Evidence</dt><dd>${esc(j.verification)} <a href="${esc(j.evidenceUrl)}" target="_blank" rel="noopener noreferrer">Source evidence ↗</a></dd></dl><p>Availability may change after checking. Confirm location, work authorization and requirements with the employer.</p></details></article>`;}
  function sources(){return `<div class="market-method"><section class="market-card"><h2>Read the sample correctly</h2><p>Research date: <strong>${data.researchedAt}</strong> · ${esc(data.scope)}</p><ol>${data.methodology.map(m=>`<li>${esc(m)}</li>`).join('')}</ol><p>Searches cover senior automation, Blue Prism, C#/.NET desktop development, internal engineering tools, applied AI integration, technical leadership, automation business analysis and transformation. Coverage is uneven; Europe, India and Southeast Asia are better represented than East Asia. Current results include 10 newly checked roles and fit reviews of the 26 original advertisements. Countries without collected ads are not measured.</p><a class="secondary-button" href="data/rpa-vacancies.json" download>Download complete research JSON ↓</a></section><section class="market-card"><h2>Source register</h2><p>Every included advertisement has its own source link, check date and evidence route. “Listed” is not a hiring guarantee.</p><div class="source-register">${data.jobs.map(j=>`<div><a href="${esc(j.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(j.company)} · ${esc(j.title)} ↗</a><span>${esc(j.country)} · ${esc(j.sourceType)} · checked ${j.checkedAt}</span></div>`).join('')}</div></section><section class="market-card"><h2>Selected exclusions</h2><p>Examples of leads removed during verification. These are outside every dashboard total.</p>${data.excluded.map(e=>`<div class="excluded-source"><strong>${esc(e.reason)}</strong><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)} ↗</a><p>${esc(e.detail)}</p></div>`).join('')}</section></div>`;}
  function repaint(){const old=document.querySelector('.market');if(old)old.outerHTML=render();}
  function profileBanner(){return `<div class="profile-banner"><div><strong>Profile-led search · beyond RPA</strong><p>${data.jobs.filter(recommended).length} roles to review first, across automation, software engineering and adjacent careers. Fit describes technical overlap; required language levels and work eligibility still need checking.</p></div><button class="secondary-button" data-market-tab="profile">View career assessment →</button></div>`;}
  function fitSummary(j){if(!j.fit)return '';return `<section class="vacancy-fit" aria-label="Profile fit assessment"><div><span class="fit-badge ${j.fit.band==='Strong technical fit'?'strong':j.fit.band==='Potential fit'?'potential':'stretch'}">${esc(j.fit.band)}</span><span>${esc(j.fit.track)}</span></div><p><strong>Why it fits:</strong> ${j.fit.strengths.map(esc).join(' ')}</p><p><strong>Check first:</strong> ${j.fit.checks.map(esc).join(' ')}</p></section>`;}
  function profileView(){const p=data.profile;if(!p)return '<p>Profile assessment unavailable.</p>';const items=(rows)=>rows.map(r=>`<article class="profile-evidence"><h3>${esc(r.title)}</h3><p>${esc(r.detail||r.evidence)}</p><small>${esc(r.source)}</small></article>`).join('');return `<div class="career-profile"><section class="market-card profile-intro"><div class="eyebrow">CAREER ASSESSMENT · ${p.reviewedAt}</div><h2>${esc(p.headline)}</h2><p>${esc(p.summary)}</p><div class="profile-metrics">${Object.entries(rank).map(([band])=>`<button data-market-fit="${esc(band)}"><strong>${data.jobs.filter(j=>j.fit?.band===band).length}</strong><span>${esc(band)}</span></button>`).join('')}</div><p class="profile-source">${esc(p.source)} <a href="${esc(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">Referenced profile ↗</a></p></section><section class="market-card"><h2>Target roles & languages</h2><p>${esc(p.targetRoles.join(' · '))}</p><p>${esc(p.targetRolesSource)}</p><div class="profile-evidence-grid">${p.languages.map(l=>`<article class="profile-evidence"><h3>${esc(l.language)}</h3><p>${esc(l.level)}</p></article>`).join('')}</div><p>${esc(p.languageSource)}</p></section><section class="market-card"><h2>Where to search next</h2><p>Career tracks follow visible evidence, with the conditions needed for adjacent roles.</p><div class="profile-tracks">${p.tracks.map(t=>`<article><span>${esc(t.priority)}</span><h3>${esc(t.name)}</h3><p>${esc(t.why)}</p></article>`).join('')}</div></section><section class="market-card"><h2>What the profile supports</h2><div class="profile-evidence-grid">${items(p.strengths)}</div></section><section class="market-card"><h2>Experience, without inflating tenure</h2>${p.timeline.map(r=>`<article class="profile-evidence"><h3>${esc(r.title)}</h3><strong>${esc(r.employer)} · ${esc(r.dates)}</strong><p>${esc(r.evidence)}</p><small>${esc(r.source)}</small></article>`).join('')}</section><div class="profile-evidence-grid"><section class="market-card"><h2>Education & language evidence</h2>${items(p.education)}</section><section class="market-card"><h2>Certification status</h2>${items(p.certifications)}</section></div><section class="market-card"><h2>What still needs confirmation</h2><ul class="profile-checks">${p.unknowns.map(u=>`<li>${esc(u)}</li>`).join('')}</ul></section><section class="market-card"><h2>How fit is assessed</h2><p>${esc(p.methodology)}</p><p>Europe and Asia remain in scope, across all work arrangements. The recommended view prioritizes direct and plausible fits; stretch and lower-priority roles remain available through the Profile fit filter. Updates are manual research snapshots, not an automatically refreshed or exhaustive feed.</p></section></div>`;}
  function refreshResults(){const el=document.querySelector('#market-results');if(el)el.innerHTML=results();}
  async function load(){error='';try{const r=await fetch('data/rpa-vacancies.json',{cache:'no-cache'});if(!r.ok)throw Error();const incoming=await r.json();if(incoming.schemaVersion!==1||!Array.isArray(incoming.jobs))throw Error();data=incoming;window.dispatchEvent(new Event('market-ready'));repaint();}catch{error='The research collection could not be loaded. Your personal notes are still available.';repaint();}}
  document.addEventListener('input',e=>{if(e.target.dataset.marketFilter==='query'){filters.query=e.target.value;refreshResults();}});
  document.addEventListener('world-map-select',e=>{filters.country=e.detail.country;tab='vacancies';repaint();document.querySelector('#market-tab-vacancies')?.focus();});
  document.addEventListener('change',e=>{const key=e.target.dataset.marketFilter;if(!key||key==='query')return;filters[key]=key==='salary'?(e.target.checked?'yes':''):e.target.value;if(key==='region'){filters.country='';repaint();}else refreshResults();});
  document.addEventListener('keydown',e=>{const button=e.target.closest('[role="tab"][data-market-tab]');if(!button||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ids=['overview','vacancies','profile','sources'],i=ids.indexOf(tab);tab=e.key==='Home'?ids[0]:e.key==='End'?ids[ids.length-1]:ids[(i+(e.key==='ArrowRight'?1:ids.length-1))%ids.length];repaint();document.querySelector(`#market-tab-${tab}`)?.focus();});
  document.addEventListener('click',e=>{
    const fit=e.target.closest('[data-market-fit]');if(fit){Object.keys(filters).forEach(k=>filters[k]='');filters.fit=fit.dataset.marketFit;tab='vacancies';repaint();document.querySelector('#market-tab-vacancies')?.focus();return;}
    const target=e.target.closest('[data-market-tab],[data-market-facet],[data-market-action],[data-market-country],[data-market-clear]');if(!target)return;
    if(target.dataset.marketTab){tab=target.dataset.marketTab;repaint();document.querySelector(`#market-tab-${tab}`)?.focus();}
    if(target.dataset.marketFacet){filters[target.dataset.marketFacet]=target.dataset.value;repaint();}
    if(target.dataset.marketCountry){filters.country=target.dataset.marketCountry;filters.tool=target.dataset.marketTool;tab='vacancies';repaint();}
    if(target.dataset.marketClear){filters[target.dataset.marketClear]='';if(target.dataset.marketClear==='region')filters.country='';repaint();}
    if(target.dataset.marketAction==='clear'){Object.keys(filters).forEach(k=>filters[k]='');repaint();}
    if(target.dataset.marketAction==='retry'){load();repaint();}
    if(target.dataset.marketAction==='export'&&data){const blob=new Blob([JSON.stringify({researchedAt:data.researchedAt,filters:{...filters},methodology:data.methodology,profile:data.profile,jobs:selected()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mind-job-research-2026-09-23.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  });
  load();
  return {render,home};
})();
