/* Article synthesis is separate from the private-brief mechanism register. */
(() => {
  'use strict';
  const article='https://doi.org/10.1017/pls.2026.10020';
  const undp='https://hdr.undp.org/sites/default/files/2025_HDR/hdr2025_technical_notes.pdf';
  const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
  function render(){return `<section class="gender-research reproduction-study" aria-labelledby="reproduction-title">
    <div class="eyebrow">JOURNAL ARTICLE · REVIEWED 30 SEP 2026</div>
    <h2 id="reproduction-title" tabindex="-1">Fertility, partnership and solo parenthood</h2>
    <p>${link(article,'Toward individualistic reproduction: Solving the fertility crisis could require a further marginalization of men')}<br>Mads Larsen, Leif Edward Ottesen Kennair & Maryanne L. Fisher · <em>Politics and the Life Sciences</em> · 24 April 2026.</p>
    <aside class="research-boundary"><strong>Argument and descriptive analysis, not a policy trial</strong><p>The authors hypothesize that economic independence changes partner selection, weakening pair formation. They propose testing financial support, communal housing and childcare for voluntary solo parenthood, alongside support for couples. They predict further exclusion of some men; reproductive technologies are speculative countermeasures.</p></aside>
    <div class="insight-grid">
      <figure class="insight-card reproduction-diagram"><figcaption><span class="concept-label">AUTHORS’ HYPOTHESIS · NOT A MEASURED CAUSAL CHAIN</span><h3>The proposed pathway</h3></figcaption><ol class="mechanism-flow"><li>Economic independence and free partner choice</li><li>More selective matching; apps may amplify it</li><li>Fewer stable partnerships</li><li>Contraception separates sex from births</li><li>Lower realized fertility</li></ol><p>${link(article,'Article · Introduction, mating strategies and Conclusion')}</p></figure>
      <article class="insight-card reproduction-stat"><span class="concept-label">REPORTED ASSOCIATION · FIGURE 4</span><h3>Gender inequality × fertility</h3><div class="fertility-value">r ≈ +0.81</div><p>Pearson correlation · 172 countries · 2023 observations.<br>Spearman rank correlation: ≈ +0.86.</p><p>Higher inequality accompanies higher fertility; equivalently, greater equality accompanies lower fertility.</p><p>${link(article,'Article · Figure 4; UN / UNDP inputs')}</p><p class="insight-note">Reported by the authors, not independently recalculated here. No country scatterplot is reconstructed from a correlation coefficient.</p></article>
    </div>
    <div class="concept-table" tabindex="0" role="region" aria-label="Reading the article: evidence and inference"><table><caption>Reading the evidence · editorial assessment</caption><thead><tr><th scope="col">Question</th><th scope="col">What to distinguish</th><th scope="col">Next research step</th></tr></thead><tbody>
    <tr><th scope="row">What does the index measure?</th><td>UNDP’s GII combines reproductive health, empowerment and labour-market indicators. It includes adolescent birth rates and maternal mortality; it is not a direct measure of individual mate choice.</td><td>Recheck the association using separate indicators and controls for development, education and region. The index’s fertility-related component makes this a particularly important robustness check.</td></tr>
    <tr><th scope="row">Does correlation identify the mechanism?</th><td>A country-level association cannot establish women’s motives, the direction of causation, or the effect of a policy. Individual and national evidence answer different questions.</td><td>Use longitudinal individual data to test whether changing preferences precede partnership and birth outcomes; compare competing explanations.</td></tr>
    <tr><th scope="row">Would the proposal raise completed fertility?</th><td>A plausible intervention is not an estimated effect. Earlier births, more births overall and transfers between family arrangements are different outcomes.</td><td>Evaluate voluntary pilots against credible comparison groups, tracking completed family size, costs, child and parent well-being, and outcomes for men.</td></tr>
    </tbody></table></div>
    <p>${link(undp,'UNDP 2025 technical notes · GII, note 4')} · The methodological cautions above are this library’s analysis, not findings attributed to UNDP.</p>
    <aside class="research-boundary"><strong>Connect this to the rest of the section</strong><p>The article acknowledges that recent Nordic declines largely occurred within relationships. Partnership formation is therefore not a complete explanation.</p><p>Use the fertility timelines below to examine trends, not to validate a psychological mechanism. The earlier briefs propose interpersonal processes; they do not independently corroborate this article. Test these levels separately before connecting them.</p></aside>
    <p class="insight-note">Source: ${link(article,'Larsen, Kennair & Fisher (2026)')} · DOI 10.1017/pls.2026.10020 · ${link('https://creativecommons.org/licenses/by/4.0/','CC BY 4.0')}. Text condensed and diagram redrawn for this library; editorial assessment added. This note does not independently verify every study cited by the article or endorse its policy proposal.</p>
    <nav class="gender-jumps" aria-label="Related gender research"><button data-gender-jump="relationship-models">Relationship hypotheses ↓</button><button data-gender-jump="fertility">Explore fertility data ↓</button></nav>
  </section>`;}
  window.MindReproductionStudy={render};
})();
