const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
const fs=require('node:fs');
const data=require('../data/rpa-vacancies.json');

(async()=>{
  assert.equal(data.schemaVersion,1);
  assert.equal(new Set(data.jobs.map(j=>j.id)).size,data.jobs.length);
  assert.equal(new Set(data.jobs.map(j=>[j.company,j.title,j.country].join('|'))).size,data.jobs.length);
  for(const job of data.jobs){
    for(const field of ['title','company','country','region','mode','level','sourceType','verification'])assert.ok(job[field],`${job.id}: ${field}`);
    assert.ok(['Europe','Asia'].includes(job.region));
    assert.ok(job.tools.length&&new Set(job.tools).size===job.tools.length);
    for(const url of [job.sourceUrl,job.evidenceUrl])assert.equal(new URL(url).protocol,'https:');
    assert.ok(job.checkedAt===data.researchedAt);
    assert.equal(job.fit.profileId,data.profile.id);
    assert.equal(job.fit.assessedAt,data.profile.reviewedAt);
    assert.ok(job.fit.strengths.length && job.fit.checks.length);
    assert.ok(['Strong technical fit','Potential fit','Stretch','Lower priority'].includes(job.fit.band));
    if(job.postedAt)assert.ok(Date.parse(job.postedAt)<=Date.parse(job.checkedAt));
    if(job.salary)assert.ok(job.salary.min>0&&(!job.salary.max||job.salary.max>=job.salary.min));
  }
  const server=spawn(process.execPath,[path.join(__dirname,'../scripts/serve.cjs')],{env:{...process.env,PORT:'4175'},windowsHide:true});
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject)});
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1536,height:1080}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:4175');
    await page.locator('.market-kpis').waitFor();
    assert.equal(await page.locator('.rail').count(),0);
    assert.equal(await page.locator('.inspector').count(),0);
    const recommended=data.jobs.filter(j=>['Strong technical fit','Potential fit'].includes(j.fit.band));
    assert.equal(await page.locator('.market-kpis strong').first().textContent(),String(recommended.length));
    const legend=page.locator('.country-pie-legend');
    assert.equal(await legend.locator('strong').evaluateAll(nodes=>nodes.reduce((sum,n)=>sum+Number(n.textContent),0)),recommended.length);
    assert.equal(await legend.locator('button').count(),new Set(recommended.map(j=>j.country)).size);
    const lithuaniaColor=await legend.getByRole('button',{name:/View Lithuania:/}).locator('i').evaluate(el=>getComputedStyle(el).backgroundColor);
    await page.locator('.country-pie-card').screenshot({path:'test-results/country-pie-desktop.png'});
    await page.getByLabel('Countries',{exact:true}).selectOption('Lithuania');
    assert.equal(await page.locator('.country-pie-layout svg circle').count(),1,'Single country renders a full pie');
    assert.equal(await legend.locator('i').evaluate(el=>getComputedStyle(el).backgroundColor),lithuaniaColor,'Country colors stay stable across filters');
    await legend.getByRole('button',{name:/View Lithuania:/}).click();
    assert.equal(await page.locator('.vacancy-card').count(),recommended.filter(j=>j.country==='Lithuania').length);
    await page.getByRole('button',{name:/new this search →/}).click();
    assert.equal(await page.locator('.vacancy-card').count(),data.refresh.newRecords);
    assert.equal(await page.locator('.new-vacancy').count(),data.refresh.newRecords);
    await page.getByRole('tab',{name:'Career fit',exact:true}).click();
    assert.match(await page.locator('.career-profile').textContent(),/expired June 2023/);
    assert.match(await page.locator('.career-profile').textContent(),/Developer · Manager · Team lead · Analyst · Product owner/);
    for(const language of ['Russian','English','Lithuanian','French','Japanese'])assert.ok(await page.getByRole('heading',{name:language,exact:true}).isVisible());
    assert.match(await page.locator('.career-profile').textContent(),/A little Japanese/);
    assert.match(await page.locator('.career-profile').textContent(),/not evidence of current B2 fluency/);
    await page.screenshot({path:'test-results/profile-desktop.png'});
    await page.getByRole('tab',{name:'Career fit',exact:true}).press('End');
    assert.equal(await page.getByRole('tab',{name:'Sources & method'}).getAttribute('aria-selected'),'true');
    await page.getByRole('tab',{name:'Sources & method'}).press('ArrowLeft');
    assert.equal(await page.getByRole('tab',{name:'Career fit',exact:true}).getAttribute('aria-selected'),'true');
    await page.getByRole('tab',{name:'Career fit',exact:true}).press('ArrowLeft');
    assert.equal(await page.getByRole('tab',{name:/Vacancies/}).getAttribute('aria-selected'),'true');
    await page.getByLabel('Countries',{exact:true}).selectOption('Malaysia');
    await page.getByRole('tab',{name:'Career fit',exact:true}).click();
    await page.getByRole('button',{name:/Strong technical fit/}).click();
    assert.equal(await page.locator('.vacancy-card').count(),data.jobs.filter(j=>j.fit.band==='Strong technical fit').length,'Career metrics clear unrelated filters');
    assert.equal(await page.locator('.vacancy-fit').count(),await page.locator('.vacancy-card').count());
    await page.getByLabel('Career tracks',{exact:true}).selectOption('C#/.NET desktop and internal platforms');
    assert.equal(await page.locator('.vacancy-card').count(),1);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    assert.equal(await page.locator('.market-kpis strong').first().textContent(),String(data.jobs.length));
    await page.screenshot({path:'test-results/market-desktop.png',fullPage:false});
    await page.getByLabel('Regions',{exact:true}).selectOption('Asia');
    const asian=data.jobs.filter(j=>j.region==='Asia');
    assert.equal(await page.locator('.market-kpis strong').first().textContent(),String(asian.length));
    await page.getByLabel('Countries',{exact:true}).selectOption('Malaysia');
    await page.getByRole('tab',{name:/Vacancies/}).click();
    assert.equal(await page.locator('.vacancy-card').count(),data.jobs.filter(j=>j.country==='Malaysia').length);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByLabel('Search vacancies',{exact:true}).fill('a-nonexistent-employer');
    await page.getByRole('heading',{name:'No matching vacancies'}).waitFor();
    await page.getByRole('button',{name:'Show all vacancies'}).click();
    assert.equal(await page.locator('.vacancy-card').count(),data.jobs.length);
    await page.locator('.more-filters summary').click();
    await page.getByLabel('Disclosed salary only').check();
    assert.equal(await page.locator('.vacancy-card').count(),data.jobs.filter(j=>j.salary).length);
    const download=page.waitForEvent('download');
    await page.getByRole('button',{name:'Export results'}).click();
    const file=await download;const exported=JSON.parse(fs.readFileSync(await file.path()));
    assert.equal(exported.jobs.length,data.jobs.filter(j=>j.salary).length);
    assert.ok(exported.methodology.length);
    assert.equal(exported.profile.id,data.profile.id);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    const cell=page.locator('[data-market-country]').first(),country=await cell.getAttribute('data-market-country'),tool=await cell.getAttribute('data-market-tool');
    await cell.click();
    assert.equal(await page.locator('.vacancy-card').count(),data.jobs.filter(j=>j.country===country&&j.tools.includes(tool)).length);
    await page.getByRole('tab',{name:'Sources & method'}).click();
    assert.equal(await page.locator('.source-register a').count(),data.jobs.length);
    assert.equal(await page.locator('.excluded-source').count(),data.excluded.length);
    await page.getByRole('tab',{name:'Sources & method'}).press('Home');
    assert.equal(await page.getByRole('tab',{name:'Overview',exact:true}).getAttribute('aria-selected'),'true');
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'test-results/market-mobile.png',fullPage:false});
    await page.locator('.country-pie-card').screenshot({path:'test-results/country-pie-mobile.png'});
    await page.getByRole('tab',{name:'Career fit',exact:true}).click();
    await page.screenshot({path:'test-results/profile-mobile.png'});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Career assessment fits mobile');
    await page.locator('.content-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);
    assert.ok(await page.getByRole('heading',{name:'How fit is assessed'}).isVisible());
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow');
    assert.equal(errors.length,0,errors.join('\n'));
    const offline=await browser.newPage();
    await offline.route('**/data/rpa-vacancies.json',r=>r.abort());
    await offline.goto('http://127.0.0.1:4175/#view=market');
    await offline.getByRole('button',{name:'Retry loading research'}).waitFor();
    await offline.unroute('**/data/rpa-vacancies.json');
    await offline.getByRole('button',{name:'Retry loading research'}).click();
    await offline.locator('.market-kpis').waitFor();
    await page.setViewportSize({width:1440,height:720});
    await page.getByRole('tab',{name:/Vacancies/}).click();
    const scroll=page.locator('.content-scroll');
    await scroll.evaluate(el=>el.scrollTop=el.scrollHeight);
    assert.ok(await scroll.evaluate(el=>el.scrollHeight>el.clientHeight && Math.abs(el.scrollHeight-el.clientHeight-el.scrollTop)<2),'Listings scroll to the end');
    assert.ok(await page.locator('.topbar').evaluate(el=>el.getBoundingClientRect().top===0),'Header stays fixed');
    console.log(`PASS: ${data.jobs.length} source records, filters, counts, matrix drill-down, export, mobile layout, load recovery.`);
  }finally{await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
