const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
const data=require('../data/rpa-vacancies.json');
const geometry=require('../data/world-map.json');
const counts=Object.fromEntries([...new Set(data.jobs.map(j=>j.country))].map(name=>[name,data.jobs.filter(j=>j.country===name).length]));

(async()=>{
  for(const name of Object.keys(counts))assert.ok(geometry.countries.some(c=>c.name===name),'Geometry for '+name);
  assert.ok(geometry.countries.length>200);
  const server=spawn(process.execPath,[path.join(__dirname,'../scripts/serve.cjs')],{env:{...process.env,PORT:'4176'},windowsHide:true});
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject)});
  const browser=await chromium.launch();
  try{
    const page=await browser.newPage({viewport:{width:1536,height:1080}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:4176/#view=market');
    await page.locator('.world-map-count').first().waitFor();
    const map=page.locator('mind-world-map');
    assert.equal(await map.locator('.world-map-count').evaluateAll(nodes=>nodes.reduce((sum,n)=>sum+Number(n.dataset.count),0)),data.jobs.filter(j=>['Strong technical fit','Potential fit'].includes(j.fit.band)).length,'Default map follows recommended fit');
    await page.getByLabel('Profile fit',{exact:true}).selectOption('');
    await map.locator('.world-map-count').first().waitFor();
    assert.equal(await map.locator('.world-map-country').count(),geometry.countries.length);
    assert.equal(await map.locator('.has-vacancies').count(),Object.keys(counts).length);
    assert.equal(await map.locator('.world-map-count').count(),Object.keys(counts).length);
    assert.equal(await map.locator('.world-map-count').evaluateAll(nodes=>nodes.reduce((sum,n)=>sum+Number(n.dataset.count),0)),data.jobs.length);
    for(const [country,n] of Object.entries(counts))assert.equal(await map.locator(`.world-map-country[data-map-country="${country}"]`).getAttribute('data-count'),String(n));
    const colors=await map.locator('.has-vacancies').evaluateAll(nodes=>Object.fromEntries(nodes.map(n=>[n.dataset.count,getComputedStyle(n).fill])));
    assert.equal(new Set(Object.values(colors)).size,new Set(Object.values(counts)).size,'Distinct density shades follow country totals');
    const overlaps=await map.locator('.world-map-count').evaluateAll(nodes=>{
      const boxes=nodes.map(n=>n.getBoundingClientRect());return boxes.some((a,i)=>boxes.some((b,j)=>i<j&&Math.hypot((a.left+a.right-b.left-b.right)/2,(a.top+a.bottom-b.top-b.bottom)/2)<24));
    });assert.equal(overlaps,false,'World count labels must not overlap');
    await page.locator('.world-map-section').scrollIntoViewIfNeeded();
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-desktop.png'});
    await map.getByRole('button',{name:'Europe',exact:true}).click();
    assert.equal(await map.locator('.world-map-scale').textContent(),'4×');
    const lithuania=map.locator('.world-map-count[data-map-country="Lithuania"]');
    await lithuania.focus();
    assert.ok((await map.locator('.world-map-inspection').textContent()).includes('Lithuania · '+counts.Lithuania));
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-europe.png'});
    await lithuania.press('Enter');
    const popup=map.getByRole('dialog');
    assert.equal(await popup.locator('a').count(),counts.Lithuania);
    assert.equal(await page.getByRole('tab',{name:'Overview',exact:true}).getAttribute('aria-selected'),'true');
    assert.equal(await page.getByLabel('Countries',{exact:true}).inputValue(),'');
    const links=await popup.locator('a').evaluateAll(nodes=>nodes.map(n=>n.href));
    assert.deepEqual(links.sort(),data.jobs.filter(j=>j.country==='Lithuania').map(j=>j.sourceUrl).sort());
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-popover-desktop.png'});
    const firstLink=popup.locator('a').first(),destination=await firstLink.getAttribute('href');
    await page.context().route(destination,r=>r.fulfill({body:'Vacancy destination'}));
    const opened=page.waitForEvent('popup');await firstLink.click();const jobPage=await opened;await jobPage.waitForLoadState();
    assert.equal(jobPage.url(),destination);await jobPage.close();
    await page.keyboard.press('Escape');assert.equal(await popup.count(),0);
    assert.ok(await lithuania.evaluate(el=>el===document.activeElement));
    await lithuania.press(' ');await popup.waitFor();
    await map.getByRole('button',{name:'Close country vacancies'}).click();assert.equal(await popup.count(),0);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    await map.locator('.world-map-count').first().waitFor();
    await map.getByRole('button',{name:'Reset world map'}).click();
    await page.getByLabel('Tools',{exact:true}).selectOption('UiPath');
    await map.locator('.world-map-count').first().waitFor();
    assert.equal(await map.locator('.world-map-count').evaluateAll(nodes=>nodes.reduce((sum,n)=>sum+Number(n.dataset.count),0)),data.jobs.filter(j=>j.tools.includes('UiPath')).length);
    await map.locator('.world-map-count[data-map-country="Lithuania"]').click();
    assert.equal(await popup.locator('a').count(),data.jobs.filter(j=>j.country==='Lithuania'&&j.tools.includes('UiPath')).length);
    await page.locator('.world-map-heading').click();assert.equal(await popup.count(),0);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    await map.locator('.world-map-count').first().waitFor();
    await map.getByRole('button',{name:'Zoom map in'}).click();
    await map.locator('svg').scrollIntoViewIfNeeded();
    const before=await map.locator('.world-map-geography').getAttribute('transform');
    const rect=await map.locator('svg').boundingBox();
    await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);
    await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+80,rect.y+rect.height/2+30,{steps:5});await page.mouse.up();
    await page.waitForFunction(old=>document.querySelector('.world-map-geography').getAttribute('transform')!==old,before);
    await map.getByRole('button',{name:'Reset world map'}).click();
    await map.locator('svg').focus();await map.locator('svg').press('+');
    assert.equal(await map.locator('.world-map-scale').textContent(),'1.5×');
    await map.locator('svg').press('Home');
    assert.equal(await map.locator('.world-map-scale').textContent(),'1×');
    await map.locator('svg').hover();
    const scrollBeforeZoom=await page.locator('.content-scroll').evaluate(el=>el.scrollTop);
    await page.mouse.wheel(0,-200);
    await page.waitForFunction(()=>document.querySelector('mind-world-map').view.zoom>1);
    assert.equal(await page.locator('.content-scroll').evaluate(el=>el.scrollTop),scrollBeforeZoom,'Wheel over map does not scroll page');
    await page.mouse.wheel(0,200);
    await page.waitForFunction(()=>Math.abs(document.querySelector('mind-world-map').view.zoom-1)<.001);
    await map.locator('svg').dispatchEvent('wheel',{deltaY:-5000,deltaMode:1});
    assert.ok(await map.evaluate(el=>el.view.zoom<=10));
    await map.getByRole('button',{name:'Reset world map'}).click();
    await page.setViewportSize({width:390,height:844});
    await page.locator('.world-map-section').scrollIntoViewIfNeeded();
    await page.waitForFunction(()=>document.querySelector('mind-world-map svg').viewBox.baseVal.width<400);
    assert.equal(await map.locator('.world-map-count').count(),Object.keys(counts).length,'Small countries keep labels on mobile');
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-mobile.png'});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    const priorScroll=await page.locator('.content-scroll').evaluate(el=>el.scrollTop);
    await map.locator('svg').hover();await page.mouse.wheel(0,-200);
    await page.waitForFunction(()=>document.querySelector('mind-world-map').view.zoom>1);
    assert.equal(await page.locator('.content-scroll').evaluate(el=>el.scrollTop),priorScroll);
    await page.locator('.world-map-heading').hover();await page.mouse.wheel(0,200);
    await page.waitForFunction(before=>document.querySelector('.content-scroll').scrollTop>before,priorScroll);
    await map.getByRole('button',{name:'Asia',exact:true}).click();
    await map.locator('.world-map-count[data-map-country="Singapore"]').click();
    assert.equal(await popup.locator('a').count(),counts.Singapore);
    const zoomBeforeList=await map.evaluate(el=>el.view.zoom);
    await popup.locator('ul').hover();await page.mouse.wheel(0,600);
    await page.waitForFunction(()=>document.querySelector('.world-map-jobs ul').scrollTop>0);
    assert.equal(await map.evaluate(el=>el.view.zoom),zoomBeforeList,'Scrolling job list does not zoom map');
    await popup.locator('a').last().scrollIntoViewIfNeeded();
    const bounds=await popup.boundingBox(),canvasBounds=await map.locator('.world-map-canvas').boundingBox();
    assert.ok(bounds.x>=canvasBounds.x&&bounds.x+bounds.width<=canvasBounds.x+canvasBounds.width);
    assert.ok(bounds.height<=canvasBounds.height);
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-popover-mobile.png'});
    await page.keyboard.press('Escape');
    await map.locator('.world-map-accessible summary').click();
    await map.locator('.world-map-accessible button[data-map-country="India"]').click();
    assert.equal(await popup.locator('a').count(),counts.India,'Country totals open every matching vacancy');
    await map.locator('.world-map-accessible button[data-map-country="Lithuania"]').click();
    assert.equal(await popup.locator('a').count(),counts.Lithuania,'Selecting another country replaces the list');
    const offline=await browser.newPage();
    await offline.route('**/data/world-map.json',r=>r.abort());
    await offline.goto('http://127.0.0.1:4176/#view=market');
    await offline.getByRole('button',{name:'Retry map',exact:true}).waitFor();
    assert.ok(await offline.locator('.market-bars').count()>0,'Map errors do not block charts');
    await offline.unroute('**/data/world-map.json');
    await offline.getByRole('button',{name:'Retry map',exact:true}).click();
    await offline.locator('.world-map-count').first().waitFor();
    assert.deepEqual(errors,[]);
    console.log('PASS: map geography, counts, density, non-overlapping labels, filters, country job popovers, direct vacancy links, keyboard, direct wheel zoom, outside-map scrolling, mobile and load recovery.');
  }finally{await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
