const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
const data=require('../data/rpa-vacancies.json');
const geometry=require('../data/world-map.json');
const counts=Object.fromEntries([...new Set(data.jobs.map(j=>j.country))].map(name=>[name,data.jobs.filter(j=>j.country===name).length]));

(async()=>{
  for(const name of Object.keys(counts))assert.ok(geometry.countries.some(c=>c.name===name),'Geometry for '+name);
  assert.ok(geometry.countries.length>200);
  const server=spawn(process.execPath,[path.join(__dirname,'../scripts/serve.cjs')],{env:{...process.env,PORT:'4176'},windowsHide:true});
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject)});
  const browser=await chromium.launch();
  try{
    const page=await browser.newPage({viewport:{width:1536,height:1080}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:4176/#view=market');
    await page.locator('.world-map-count').first().waitFor();
    const map=page.locator('mind-world-map');
    assert.equal(await map.locator('.world-map-country').count(),geometry.countries.length);
    assert.equal(await map.locator('.has-vacancies').count(),Object.keys(counts).length);
    assert.equal(await map.locator('.world-map-count').count(),Object.keys(counts).length);
    assert.equal(await map.locator('.world-map-count').evaluateAll(nodes=>nodes.reduce((sum,n)=>sum+Number(n.dataset.count),0)),data.jobs.length);
    for(const [country,n] of Object.entries(counts))assert.equal(await map.locator(`.world-map-country[data-map-country="${country}"]`).getAttribute('data-count'),String(n));
    const colors=await map.locator('.has-vacancies').evaluateAll(nodes=>Object.fromEntries(nodes.map(n=>[n.dataset.count,getComputedStyle(n).fill])));
    assert.equal(new Set(Object.values(colors)).size,3,'Three distinct density shades');
    const overlaps=await map.locator('.world-map-count').evaluateAll(nodes=>{
      const boxes=nodes.map(n=>n.getBoundingClientRect());return boxes.some((a,i)=>boxes.some((b,j)=>i<j&&Math.hypot((a.left+a.right-b.left-b.right)/2,(a.top+a.bottom-b.top-b.bottom)/2)<24));
    });assert.equal(overlaps,false,'World count labels must not overlap');
    await page.locator('.world-map-section').scrollIntoViewIfNeeded();
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-desktop.png'});
    await map.getByRole('button',{name:'Europe',exact:true}).click();
    assert.equal(await map.locator('.world-map-scale').textContent(),'4×');
    const lithuania=map.locator('.world-map-count[data-map-country="Lithuania"]');
    await lithuania.focus();
    assert.match(await map.locator('.world-map-inspection').textContent(),/Lithuania · 3/);
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-europe.png'});
    await lithuania.press('Enter');
    assert.equal(await page.locator('.vacancy-card').count(),counts.Lithuania);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    await map.locator('.world-map-count').first().waitFor();
    await map.getByRole('button',{name:'Reset world map'}).click();
    await page.getByLabel('Tools',{exact:true}).selectOption('UiPath');
    await map.locator('.world-map-count').first().waitFor();
    assert.equal(await map.locator('.world-map-count').evaluateAll(nodes=>nodes.reduce((sum,n)=>sum+Number(n.dataset.count),0)),data.jobs.filter(j=>j.tools.includes('UiPath')).length);
    await map.locator('.world-map-count[data-map-country="Lithuania"]').click();
    assert.equal(await page.locator('.vacancy-card').count(),data.jobs.filter(j=>j.country==='Lithuania'&&j.tools.includes('UiPath')).length);
    await page.getByRole('button',{name:'Reset filters',exact:true}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).click();
    await map.locator('.world-map-count').first().waitFor();
    await map.getByRole('button',{name:'Zoom map in'}).click();
    await map.locator('svg').scrollIntoViewIfNeeded();
    const before=await map.locator('.world-map-geography').getAttribute('transform');
    const rect=await map.locator('svg').boundingBox();
    await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);
    await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+80,rect.y+rect.height/2+30,{steps:5});await page.mouse.up();
    await page.waitForFunction(old=>document.querySelector('.world-map-geography').getAttribute('transform')!==old,before);
    await map.getByRole('button',{name:'Reset world map'}).click();
    await map.locator('svg').focus();await map.locator('svg').press('+');
    assert.equal(await map.locator('.world-map-scale').textContent(),'1.5×');
    await map.locator('svg').press('Home');
    assert.equal(await map.locator('.world-map-scale').textContent(),'1×');
    await page.setViewportSize({width:390,height:844});
    await page.locator('.world-map-section').scrollIntoViewIfNeeded();
    await page.waitForFunction(()=>document.querySelector('mind-world-map svg').viewBox.baseVal.width<400);
    assert.equal(await map.locator('.world-map-count').count(),Object.keys(counts).length,'Small countries keep labels on mobile');
    await page.locator('.world-map-section').screenshot({path:'test-results/world-map-mobile.png'});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    const priorScroll=await page.locator('.content-scroll').evaluate(el=>el.scrollTop);
    await map.locator('svg').hover();await page.mouse.wheel(0,200);
    await page.waitForFunction(before=>document.querySelector('.content-scroll').scrollTop>before,priorScroll);
    await map.getByRole('button',{name:'Asia',exact:true}).click();
    await map.locator('.world-map-count[data-map-country="Singapore"]').click();
    assert.equal(await page.locator('.vacancy-card').count(),counts.Singapore);
    const offline=await browser.newPage();
    await offline.route('**/data/world-map.json',r=>r.abort());
    await offline.goto('http://127.0.0.1:4176/#view=market');
    await offline.getByRole('button',{name:'Retry map',exact:true}).waitFor();
    assert.ok(await offline.locator('.market-bars').count()>0,'Map errors do not block charts');
    await offline.unroute('**/data/world-map.json');
    await offline.getByRole('button',{name:'Retry map',exact:true}).click();
    await offline.locator('.world-map-count').first().waitFor();
    assert.deepEqual(errors,[]);
    console.log('PASS: map geography, counts, density, non-overlapping labels, filters, keyboard, zoom/pan, mobile, ordinary page scrolling and load recovery.');
  }finally{await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
